### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long

### ISSUE THREAD

**Issue by jerrynavi** [Azure-Samples/azure-ai-vision-sdk#82]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

When integrating Face Analysis into my application, I encounter the following error while trying to create a FaceAnalysisOptions instance:

```
java.lang.UnsatisfiedLinkError: No implementation found for long com.azure.ai.vision.common.internal.implementation.PropertiesJNI.corePropertiesCreateHandle(com.azure.ai.vision.common.internal.implementation.IntRef) (tried Java_com_azure_ai_vision_common_internal_implementation_PropertiesJNI_corePropertiesCreateHandle and Java_com_azure_ai_vision_common_internal_implementation_PropertiesJNI_corePropertiesCreateHandle__Lcom_azure_ai_vision_common_internal_implementation_IntRef_2) - is the library loaded, e.g. System.loadLibrary?
	at com.azure.ai.vision.common.internal.implementation.PropertiesJNI.corePropertiesCreateHandle(Native Method)
	at com.azure.ai.vision.common.internal.implementation.PropertiesJNI.createPropertiesHandle(PropertiesJNI.java:28)
	at com.azure.android.ai.vision.faceanalyzer.FaceAnalysisOptions.<init>(FaceAnalysisOptions.java:21)
	at com.omniasig.app.AnalyzeActivity.startAnalyzeOnce(AnalyzeActivity.kt:299)
``` 

### Expected/desired behavior
>

FaceAnalysisOptions should be created without any issues.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Ubuntu 22.04

### Versions
>
com.azure.ai:azure-ai-vision-common:0.16.0-beta.1
com.azure.ai:azure-ai-vision-faceanalyzer:0.16.0-beta.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jerrynavi** [comment]
Thanks for replying @dipidoo.

Updating to 0.16.2-beta.2, I get the following error. It also happens with the sample.

```
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.azure.ai:azure-ai-vision-faceanalyzer:0.16.2-beta.2, variant=com.azure.ai:azure-ai-vision-faceanalyzer:0.16.2-beta.2 configuration compile, variantName=null, artifactFile=/home/<REDACTED>/.gradle/caches/modules-2/files-2.1/com.azure.ai/azure-ai-vision-faceanalyzer/0.16.2-beta.2/f40651d62ac4dd7ca87e21785257cb83d13ea517/azure-ai-vision-faceanalyzer-0.16.2-beta.2.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=/home/<REDACTED>/Downloads/azure-ai-vision-sdk-main/samples/kotlin/face/FaceAnalyzerSample})

```

I've tried invalidating my IDE cache and restarting, but the error still persists.
